vm-t-yui/btman-int1

ModelViewerTest/Assets/InputTest.meta, ModelViewerTest/Assets/InputTest/InputLog.cs, ModelViewerTest/Assets/InputTest/InputLog.cs.meta, ModelViewerTest/Assets/InputTest/touchImage.prefab, ModelViewerTest/Assets/InputTest/touchImage.prefab.meta
タッチ操作の入力情報を取得できるテストプログラムを作成した。
タッチされた数を左下の文字列に表示できるようにした。
=> タッチ操作の入力情報の取得

.gitignore
・無視リストのgitignoreからいくつか消えていた項目があったので以下を追加しました。
確認をお願いします。
AdTest/.vs/
AdTest/Library/
*.zip
=> 無視リストに項目を追加

AdTest/Assets/AdBannerTest.cs, AdTest/Assets/AdInterstitialTest.cs, AdTest/Assets/AdManager.cs
・「AdManager.cs」のアプリIDを定数化
・「AdBannerTest.cs」「AdInterstitialTest.cs」の使用していない関数（Start、Update）の削除
=> アプリIDの定数化、使用していない関数の削除

FirstBattaManGame/Assets/Object/Scripts/ScenePhase.cs, FirstBattaManGame/Assets/Scenes/MainGame.unity
・結果を算出して表示、リザルトからタイトルへ戻る一連の処理を追加した。
【確認ファイル】
ScenePhase.cs
=> リザルト関連の処理を追加

FirstBattaManGame/Assets/Object/Scripts/ScenePhase.cs, FirstBattaManGame/Assets/Scenes/MainGame.unity
・カウントダウンの処理やカメラの動きなどの処理を加えて、フェーズの一連の流れに調整を加えた。
（現在プルリクを出している「リザルト関連の処理を追加」のマージが終わったら、こちらのマージをお願いします）
【確認ファイル】
ScenePhase.cs
=> フェーズ内の処理をいくつか追加して調整

.gitignore, GooglePlayGameTest/Assets/GoogleServiceManager.cs, GooglePlayGameTest/Assets/GoogleServiceManager.cs.meta, GooglePlayGameTest/Assets/Scenes/SampleScene.unity
・無視リストに.vsファイルが入っていなかったため、.gitignoreファイル更新
・GoogleServiceの機能を管理するクラス「GoogleServiceManager」を作成。
・上記のStartでGooglePlayへのサインインを実行。
=> GooglePlayへのサインイン機能実装。

GameCenterTest/Assets/GameCenterManager.cs, GameCenterTest/Assets/GameCenterManager.cs.meta, GameCenterTest/ProjectSettings/GraphicsSettings.asset, GameCenterTest/ProjectSettings/ProjectSettings.asset, GameCenterTest/ProjectSettings/UnityConnectSettings.asset
GameCenterのログイン、実績、リーダーボードが見れる処理を書いたGameCenterManager.csというスクリプトを作りました。
=> GameCenterのログイン、実績、リーダーボードの導入です。

FirstBattaManGame/Assets/Object/Scripts/JumpPowerGauge.cs, FirstBattaManGame/Assets/Object/Scripts/JumpPowerGauge.cs.meta, FirstBattaManGame/Assets/Scenes/MainGame.unity, FirstBattaManGame/Assets/Scenes/Title.unity
（プレイヤーまわりのコードのリファクタリングのマージが終わってからこちらのマージをお願いします）
=> ゲージとその他UIの修正

GooglePlayGameTest/.idea/workspace.xml, GooglePlayGameTest/Assets/GoogleAchievementManager.cs, GooglePlayGameTest/Assets/GoogleAchievementManager.cs.meta, GooglePlayGameTest/Assets/GoogleServiceManager.cs
・実績管理クラス「GoogleAchievementManager.cs」作成
・GoogleServiceManagerにサインイン状態のフラグを作成
=> GooglePlay実績テストプログラム追加、GoogleServiceManager修正

GooglePlayGameTest/Assets/GPGSIds.cs, GooglePlayGameTest/Assets/GoogleAchievementManager.cs, GooglePlayGameTest/Assets/GoogleLeaderboardManager.cs, GooglePlayGameTest/Assets/GoogleLeaderboardManager.cs.meta, GooglePlayGameTest/Assets/GoogleServiceManager.cs
・GooglePlayリーダーボード機能のため、リソースを追加
・サインインに失敗したら再度サインイン処理を行うように修正
・GooleAchievementクラスをプラットフォームがAndroidのときだけに制限
=> リーダーボード機能の追加、その他修正

FirstBattaManGame/Assets/Object/Scripts/StateMachine.cs, FirstBattaManGame/Assets/Object/Scripts/StateMachine.cs.meta
・VMUnityLib2のステートマシンをもとに、クラス「StateMachine」を追加し、コーディングルールに沿って調整を加えた。
（コミットのみのつもりでしたが、同時にプッシュもしてしまいました...）
【確認ファイル】
StateMachine.cs
=> ステートマシンの追加

FirstBattaManGame/Assets/LightweightRenderPipelineAsset.asset, FirstBattaManGame/Assets/LightweightRenderPipelineAsset.asset.meta, FirstBattaManGame/Assets/Object/Materials/GroundMat.mat, FirstBattaManGame/Assets/Object/Materials/PlayerMat.mat, FirstBattaManGame/Assets/Object/Scripts/Phase.meta, FirstBattaManGame/Assets/Object/Scripts/Phase/LightweightRenderPipelineAsset.asset, FirstBattaManGame/Assets/Object/Scripts/Phase/LightweightRenderPipelineAsset.asset.meta, FirstBattaManGame/Assets/Object/Scripts/StateMachine.cs, FirstBattaManGame/Assets/Object/Scripts/StateMachine.cs.meta, FirstBattaManGame/Assets/Scenes/MainGame.unity, FirstBattaManGame/Packages/manifest.json, FirstBattaManGame/ProjectSettings/GraphicsSettings.asset, FirstBattaManGame/ProjectSettings/ProjectSettings.asset, FirstBattaManGame/ProjectSettings/QualitySettings.asset
・プロジェクトにLWRPのパッケージをインポートした。
（プルリクを出している「ステートマシンの追加」がマージされた段階でこちらのマージをお願いします）
【確認ファイル】
（パッケージのインポートのみなのでなし）
=>  LWRPパッケージのインポート

GooglePlayGameTest/Assets/Script/DisplayFadeContoller.cs, GooglePlayGameTest/Assets/Script/DisplayFadeContoller.cs.meta, GooglePlayGameTest/Assets/Script/SceneChanger.cs, GooglePlayGameTest/Assets/Script/SceneChanger.cs.meta, GooglePlayGameTest/Assets/Script/ShareOtherApplication.cs
・共有時にスクリーンショットを撮影し、その写真を一緒に送信できるよう修正。実機での動作問題なし。
・シーン遷移時に画面のフェードイン・フェードアウトを行うクラスを作成。
　フェード開始処理呼び出し時にフェードインかフェードアウトか、表示するパネルの種類を指定するようになってます。（FadeColorじゃなくてPanelTypeとかに変えようかなと思ってます。）
=> 共有機能修正、シーン遷移用の画面フェード処理・シーンロード処理のスクリプト作成

BattaJump/Assets/Scenes/MainGame.unity, BattaJump/Assets/Script/Audio/SoundParameterManager.cs, BattaJump/Assets/Script/Audio/SoundParameterManager.cs.meta
サウンドパラメータを管理して、セーブとロードを行うクラス「SoundParameterManager」を作成した。
このクラス内の関数を利用して、オプション側でセーブとロードを行う。
【確認ファイル】
SoundParameterManager.cs
=> as03（１）サウンドパラメータを管理するクラスを作成

BattaJump/Assets/Script/MainPlayerAnimator.cs, BattaJump/Assets/Script/MainPlayerAnimator.cs.meta, BattaJump/Assets/Script/ResultPlayerAnimator.cs, BattaJump/Assets/Script/ResultPlayerAnimator.cs.meta, BattaJump/Assets/Script/TitlePlayerAnimator.cs, BattaJump/Assets/Script/TitlePlayerAnimator.cs.meta
・各シーンごとに下記のアニメーション制御クラスを作成
「TitlePlayerAnimator.cs」
「MainPlayerAnimator.cs」
「ResultPlayerAnimator.cs」
確認お願いします。
=> as04（２）プレイヤーのアニメーション制御クラス作成

BattaJump/Assets/Prefabs/FadeController.prefab, BattaJump/Assets/Script/DisplayFadeContoller.cs, BattaJump/Assets/Script/InputController.cs, BattaJump/Assets/Script/Phase/PhaseState.cs, BattaJump/Assets/Script/Phase/ResultPhaseState.cs, BattaJump/Assets/Script/Phase/TitlePhaseState.cs, BattaJump/Assets/Script/SceneLoader.cs, BattaJump/Assets/Script/ScoreCountUp.cs, BattaJump/Assets/Script/ScoreDraw.cs
「as04（２）プレイヤーのアニメーション制御クラス作成」がマージされたら、マージ先をmasterに変更します。
・「DisplayFadeController.cs」…ネイティブ広告を表示できるよう修正
・「InputController.cs」…フェードアウトが終わる前から入力を取るようになっていたのを修正
・「SceneLoader.cs」…ロード中にロードの進捗状況ゲージを表示するよう修正
・「ScoreCountUp.cs」…一定の間隔でカウントできるよう、Update()をFixedUpdate()に変更
・「ScoreDraw.cs」…default初期化できていなかったので修正
・「PhaseState.cs」…「InputController.cs」の変更に伴い、クラスのオンオフ処理を追加
・「ResultPhaseState.cs」…ロード中はFPSを下げるよう修正
・「TitlePhaseState.cs」…ロード中はFPSを下げるよう修正
=> as04（３）細かい機能修正

BattaJump/Assets/Script/Phase/PhaseState.cs, BattaJump/Assets/Script/Phase/ResultPhaseState.cs, BattaJump/Assets/Script/Phase/TitlePhaseState.cs
・「PhaseState.cs」「TitlePhaseState.cs」「ResultPhaseState.cs」の３つを修正
=> シーンのロード処理が何回も呼ばれていたので、フェーズを追加して対応

BattaJump/Assets/Script/Audio/AudioParameter.cs, BattaJump/Assets/Script/Audio/AudioParameterLoader.cs, BattaJump/Assets/Script/Audio/AudioParameterLoader.prefab, BattaJump/Assets/Script/Audio/AudioParameterLoader.prefab.meta, BattaJump/Assets/Script/Audio/AudioPlayController.prefab, BattaJump/Assets/Script/Audio/AudioSetting.prefab, BattaJump/Assets/Script/Audio/AudioSetting.prefab.meta, BattaJump/Assets/Script/Audio/AudioSettingUiController.cs
・オーディオパラメータのロードとセーブ、UIに反映するまでの処理で不具合が出ていたので修正した。
【確認ファイル】
AudioParameter.cs
AudioParameterLoader.cs
AudioSettingUiController.cs
=> ・オーディオパラメータのロードとセーブ機能の不具合を修正

BattaJump/Assets/Animation/Result/SighUpper.anim, BattaJump/Assets/Animation/Result/SighUpper.anim.meta, BattaJump/Assets/Animation/Result/wooden_sign.controller, BattaJump/Assets/Animation/Result/wooden_sign.controller.meta, BattaJump/Assets/CanvasActive.cs, BattaJump/Assets/CanvasActive.cs.meta, BattaJump/Assets/Prefabs/ResultPrefab/ResultCanvas_Kazuo.prefab, BattaJump/Assets/Prefabs/ResultPrefab/ResultWoodenSign.prefab, BattaJump/Assets/Prefabs/ResultPrefab/ResultWoodenSign.prefab.meta
=> リザルト時の看板設置

BattaJump/Assets/Animation/Crater/CraterGrowing.anim, BattaJump/Assets/Prefabs/SkyboxRotater.prefab, BattaJump/Assets/Prefabs/SkyboxRotater.prefab.meta, BattaJump/Assets/Script/SkyboxRotater.cs, BattaJump/Assets/Script/SkyboxRotater.cs.meta
・スカイボックスを回転させる「SkyboxRotater.cs」作成
・クレーターのアニメーションの座標を修正
上記csファイルの確認をお願いします。
=> スカイボックス回転機能作成、クレーターのアニメーション修正

BattaJump/ProjectSettings/ProjectSettings.asset, BattaJump/ProjectSettings/UnityConnectSettings.asset
UnityAdsを利用するためにプロジェクト設定を追加
各人Unityメンバー追加へのメールが飛んでいると思うので、対応したらApproveしてください
最後の人がマージしてください
=> unityadsの設定等を追加

BattaJump/Assets/Script/Audio/AudioPlayer.cs, BattaJump/Assets/Script/Audio/AudioSettingUiController.cs
・AudioPlayerクラスに特定のSEが再生中かどうか判定する関数を追加した。
・オプション画面でSEのスライダーを動かしたときにアイテム取得音が再生されるようにした。
【確認ファイル】
AudioPlayer.cs
AudioSettingUiController.cs
=> SE音量変更時のサウンド追加

BattaJump/Assets/Particle/GetItemParticle.prefab, BattaJump/Assets/Particle/GetItemParticle.prefab.meta, BattaJump/Assets/Script/DisableParticle.cs, BattaJump/Assets/Script/DisableParticle.cs.meta, BattaJump/Assets/Script/PlayerItemGetEvent.cs
アイテム取得時のパーティクルを追加しました。
見て欲しいスクリプトは
DisableParticle.cs -> パーティクルの終了検知(終了したら非表示にする)
PlayerItemGetEvent.cs -> パーティクルを表示させる処理追加
です。
=> アイテム取得パーティクル追加

BattaJump/Assets/Script/CameraMoveController.cs, BattaJump/Assets/Script/CloudCreater.cs
・「CloudCreater.cs」で、雲を生成するたびにInstantinateしていたので、最初に5個用意してそれを使いまわすよう修正
・上記に合わせて、「CameraMoveController.cs」も修正
上記2つのファイルの確認をお願いします。
=> 雲生成クラスの機能修正

BattaJump/Assets/Prefabs/AdPrefab/AdVideoRecommender.prefab, BattaJump/Assets/Script/CloudCreater.cs
・「CloudCreater.cs」の、コメント追加と条件式の修正
・AdVideoRecommenderプレハブ修正
「CloudCreater.cs」のみ確認をお願いします。
=> CloudCreater.cs修正、AdVideoRecommenderのプレハブ修正

BattaJump/Assets/Script/Ad/AdMob/AdBannerController.cs
・「AdBannerController.cs」をリザルト時は上に表示するよう修正
FileChangesは1つのみです。確認お願いします。
=> リザルト時にバナー広告を上に表示するよう修正

BattaJump/Assets/Script/Audio/AudioPlayController.prefab, BattaJump/Assets/Script/InputController.cs, BattaJump/ProjectSettings/DynamicsManager.asset
・PhysicsのGravityを弄り、ゲームスピードを調整した。
・マウスの入力処理をプリプロセッサディレクティブで判定するように変更した。
【確認ファイル】
InputController.cs
=> ゲームスピードの調整と入力処理の修正

BattaJump/Assets/Particle/TakeOff.prefab, BattaJump/Assets/Prefabs/ResultPrefab/ScoreCountUp.prefab, BattaJump/Assets/Scenes/MainGame.unity, BattaJump/Assets/Scenes/Result.unity, BattaJump/Assets/Script/Phase/JumpHeightCounter.cs, BattaJump/Assets/Script/ScoreDraw.cs
・シーンの調整
・「JumpHeightCounter.cs」「ScoreDraw.cs」を、スコアをカンマで区切るよう修正
上記2つのスクリプトの確認をお願いします。
=> シーンの調整、スコアの表記にカンマを追加

BattaJump/Assets/Scenes/MainGame.unity, BattaJump/Assets/Scenes/Result.unity
シーンでコンフリクトが起きたので、片方の変更のみを適用した。
=> シーンのコンフリクトを修正

BattaJump/Assets/ItemBoxNewTextDisplay.cs, BattaJump/Assets/ItemBoxNewTextDisplay.cs.meta, BattaJump/Assets/NewItemsDisplay.cs, BattaJump/Assets/Script/AchievementController.cs, BattaJump/Assets/Script/ItemButtonCreater.cs, BattaJump/Assets/Script/ItemDataManager.cs, BattaJump/Assets/Script/ItemDescription.cs, BattaJump/Assets/Script/ItemManager.cs
アイテムボックスのNew表示関連スクリプトを作りました。
ItemBoxNewTextDisplay.cs -> アイテムボックスのNew表示クラス
ItemDataManager.cs -> アイテムボックスのNew表示フラグの追加、関数のリネーム
ItemDescription.cs -> ボタンを押したらNewが消えるように設定
ItemManager.cs -> アイテムボックスのNew表示フラグの追加、関数のリネーム
それ以外のスクリプトはリネームした関数を合わせただけです。
=> アイテムボックスのNew表示関連スクリプト

BattaJump/Assets/Prefabs/Item/ItemBoxManager.prefab, BattaJump/Assets/Scenes/Result.unity, BattaJump/Assets/Scenes/Title.unity, BattaJump/Assets/Script/ItemButtonCreater.cs
=> 先ほどのシーンの修正

BtmanJump/Assets/NewItemsDisplay.cs, BtmanJump/Assets/Script/ShareOtherApplication.cs
NewItemsDisplay.cs -> アニメーション中にタッチするとカウントのずれが出たので、アニメーション中はタッチをカウントしないようにしました。あとエディタ用のタッチも追加しました。
ShareOtherApplication.cs -> 共有用のテキスト、URLをやってなかったのでやりました。
確認お願いします。
=> 共有機能、新規アイテム取得表示調整

BtmanJump/Assets/Script/Ad/AdMob/AdManager.cs, BtmanJump/Assets/Script/Ad/OwnCompAdInterstitialController.cs, BtmanJump/Assets/Script/AdVideoRecommender.cs, BtmanJump/Assets/Script/SignInController.cs
・「AdVideoRecommender.cs」で、UnityAdsが使用されない状況になっていたのを修正。
・その他、使用していない変数などを削除し警告を除去
変更ファイルは４つありますが、特に確認してほしいのは「AdVideoRecommender.cs」です。
よろしくお願いします。
=> UnityAdsが使用されていない不具合修正、警告除去
